### ISSUE TITLE
Authentication code do not expire

### ISSUE THREAD

**Issue by hery84** [hrax/security-totp#1]
Hi Hrax, 

In the demo, why the same (valid) authentication code always is valid? Should not be valid only during their life cycle (30 seconds) ?

/**
- Default time interval steps to check into past for validity
  */

public static final int DEFAULT_STEPS = 1;

regards from Mex.

**Comment by hrax** [comment]
Hi Mex, 

thanks for the report I haven't worked on this project for a long time. Let me have a look on it :)

Regards,
hrax

**Comment by hrax** [comment]
Hi Mex,

Can you check the latest commit? I have added tests for backwards compatibility and according to them, codes will expire in 30 seconds - 60 if using DEFAULT_STEPS = 1;

Regards,
hrax
